### ISSUE TITLE
Unable to connect to remote hosted rabbitmq 

### ISSUE THREAD

**Issue by nimtiazm** [sozu-proxy/lapin#140]
I've created a free/limited account at cloudamqp.com for testing. Following are the credentials:

Host(s): raven.rmq.cloudamqp.com (Load balanced) raven-01.rmq.cloudamqp.com
User & Vhost: tzdddsjn
Password: (please DM me)
AMQP URL: amqp://tzdddsjn:<password>@raven.rmq.cloudamqp.com/tzdddsjn

I copied the example from the following source and changed the connection details:
https://github.com/sozu-proxy/lapin/blob/master/futures/examples/client.rs 

But I can't connect to the remote server. 

I'm using rustc 1.29.2 (17a9dc751 2018-10-05) on macOS Mojave

Following is my program snippet:

```
#[macro_use] extern crate log;
extern crate lapin_futures as lapin;
extern crate futures;
extern crate tokio;

use futures::future::Future;
//use futures::Stream;
use tokio::net::TcpStream;
use tokio::runtime::Runtime;
use lapin::client::ConnectionOptions;
use std::str::FromStr;
use lapin::channel::{BasicPublishOptions,BasicProperties,QueueDeclareOptions};
use lapin::types::FieldTable;
fn main() {
    let addr = "wolverine.rmq.cloudamqp.com".parse().unwrap();

    Runtime::new().expect("runtime error!!!!").block_on(
        TcpStream::connect(&addr).and_then(|stream| {

            // connect() returns a future of an AMQP Client
            // that resolves once the handshake is done
            lapin::client::Client::connect(stream, ConnectionOptions::from_str("amqp://dsmrnnyi:<password>@wolverine.rmq.cloudamqp.com/dsmrnnyi").expect("bad conn string"))
        }).
        and_then(|(client, _ /* heartbeat */)| {

            // create_channel returns a future that is resolved
            // once the channel is successfully created
            client.create_channel()
        }).and_then(|channel| {
            let id = channel.id;
            info!("created channel with id: {}", id);

            // we using a "move" closure to reuse the channel
            // once the queue is declared. We could also clone
            // the channel
            channel.queue_declare("hello", QueueDeclareOptions::default(), FieldTable::new()).and_then(move |_| {
                info!("channel {} declared queue {}", id, "hello");

                channel.basic_publish("", "hello", b"hello from tokio".to_vec(), BasicPublishOptions::default(), BasicProperties::default())
            })
        })
    ).expect("exited with error");
}
```

Following is how I ran the program:

RUST_LOG=trace RUST_BACKTRACE=1 target/debug/q_client

Following is the output:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: AddrParseError(())', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at libstd/panicking.rs:475
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: std::panicking::try::do_call
             at libstd/panicking.rs:325
   7: core::ptr::drop_in_place
             at libcore/panicking.rs:77
   8: core::result::unwrap_failed
             at /Users/travis/build/rust-lang/rust/src/libcore/macros.rs:26
   9: <core::result::Result<T, E>>::unwrap
             at /Users/travis/build/rust-lang/rust/src/libcore/result.rs:782
  10: rand_file_read::main
             at src/main.rs:15
  11: std::rt::lang_start::{{closure}}
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  12: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  13: panic_unwind::dwarf::eh::read_encoded_pointer
             at libpanic_unwind/lib.rs:105
  14: <std::sync::mutex::Mutex<T>>::new
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  15: std::rt::lang_start
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  16: rand_file_read::main
```

**Comment by fstephany** [comment]
Does it work if you specify the port? 

    let addr = "wolverine.rmq.cloudamqp.com:5672".parse().unwrap();

**Comment by nimtiazm** [comment]
I've tried it already. It doesn't work.

**Comment by Keruspe** [comment]
This is not related to lapin.
The parse method you are calling doesn't support DNS resolution, you have to give it an IP address.

I suggest you give a look at something like https://github.com/sozu-proxy/lapin-futures-tls/blob/master/native-tls/examples/client.rs which will make all of this automatic
